export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT';
export const FORM_SUBMIT_START = 'FORM_SUBMIT_START';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL';

